name: execute
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: render dbml to svg image
        run: |
          npm install -g @softwaretechnik/dbml-renderer
          dbml-renderer -i northwind.dbml -o northwind.svg

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add northwind.svg
          git commit -m "dbml-renderer"
          git push origin master