name: execute
on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dbml render
        run: npm install -g @softwaretechnik/dbml-renderer

      - name: render dbml to svg
        run: dbml-renderer -i northwind.dbml -o northwind.svg

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: git commit
        run: |
          git add northwind.svg
          git commit -m "dbml render"
          git push origin master